fragment ParagraphEmbedMedia on ParagraphEmbedMedia {
  media: fieldMedia {
    entity {
      ...Media
    }
  }
  position: fieldPosition
  border: fieldBorderStyle
  link: fieldLink {
    url {
      path
    }
  }
}
