language: php
dist: xenial
sudo: false

php:
  - '7.2'

cache:
  directories:
    - ~/.npm
    - ~/.cache
    - ~/.composer/cache

addons:
  apt:
    packages:
      - libgconf-2-4

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - nvm install 10

install:
  - composer install
  - yarn install
  - source .envrc

script:
  - silverback setup
  - drush serve :8889 > log.txt 2>&1 &
  # Wait for drush serve to start up, but only for 20 seconds.
  - |
    DRUSH_SERVE_WAIT=0; \
    until curl -sS http://127.0.0.1:8889 >/dev/null || (($DRUSH_SERVE_WAIT > 19)); \
    do sleep 1 && \
      DRUSH_SERVE_WAIT=$(($DRUSH_SERVE_WAIT + 1)) && \
      echo "Waited $DRUSH_SERVE_WAIT seconds for drush serve."; \
    done
  - composer run-script run-tests --timeout 0

notifications:
  email: false

