fragment FooterMenu on Query {
  footerMenu: menuByName(name: "footer") {
    links {
      ...MenuItem
      links {
        ...MenuItem
        links {
          ...MenuItem
        }
      }
    }
  }
}
