fragment ParagraphLinkBgMedia on ParagraphLinkBgMedia {
  componentId: fieldParagraphId
  title: fieldTitle
  media: fieldMedia {
    entity {
      ...Media
    }
  }
  entityLinks: fieldPtLinkMulti {
    entity {
      ...ParagraphLink
    }
  }
}
