fragment ParagraphText on ParagraphText {
  componentId: fieldParagraphId
  title: fieldTitle
  tagline: fieldMetaEyebrow
  text: fieldText {
    processed
  }
  link: fieldPtLink {
    entity {
      ...ParagraphLink
    }
  }
}
