fragment ParagraphTextWithMedia on ParagraphTextWithMedia {
  text: fieldTwmText {
    entity {
      ...ParagraphText
    }
  }
  embedMedia: fieldTwmMedia {
    entity {
      ...ParagraphEmbedMedia
    }
  }
}
