<?php

/**
 * @file
 * Contains dnl_layouts.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dnl_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dnl_layouts module.
    case 'help.page.dnl_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides additional functionality for layouts.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function dnl_layouts_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_component_page_layout_builder_form':
      /*
       * When using the moderation_sidebar module, let's avoid redundant
       * clutter and remove moderation state from the vanilla LB display.
       */
      if (isset($form['moderation_state'])) {
        $form['moderation_state']['#access'] = FALSE;
      }
      if (isset($form['revision_information'])) {
        $form['revision_information']['#access'] = FALSE;
      }
      break;
  }
}
