fragment ParagraphHighlightSlide on ParagraphHighlightSlide {
  title: fieldTitle
  tagline: fieldMetaEyebrow
  entityLink: fieldPtLink {
    entity {
      ...ParagraphLink
    }
  }
  media: fieldMediaMulti {
    entity {
      ...Media
    }
  }
  position: fieldPosition
}
