fragment ParagraphTextBgMedia on ParagraphTextBgMedia {
  componentId: fieldParagraphId
  title: fieldTitle
  text: fieldText {
    processed
  }
  media: fieldMedia {
    entity {
      ...Media
    }
  }
  link: fieldPtLink {
    entity {
      ...ParagraphLink
    }
  }
}
