fragment ParagraphSlide on ParagraphSlide {
  metatitle: fieldMetaTitle
  link: fieldLink {
    title
    url {
      path
    }
  }
  media: fieldMedia {
    entity {
      ...MediaImage
      ...MediaVideo
    }
  }
  position: fieldPosition
}
