fragment ParagraphSlide on ParagraphSlide {
  title: fieldTitle
  tagline: fieldMetaEyebrow
  link: fieldLink {
    title
    url {
      path
    }
  }
  media: fieldMedia {
    entity {
      ...Media
    }
  }
  position: fieldPosition
}
