fragment ParagraphManualTeaser on ParagraphManualTeaser {
  componentId: fieldParagraphId
  title: fieldTitle
  teaserText: fieldTeaserText
  link: fieldLink {
    title
    uri
    url {
      path
      routed
    }
  }
  image: fieldImage {
    entity {
      ...MediaImage
    }
  }
}
