version: 1

update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "monthly"
    target_branch: "prod"
    version_requirement_updates: "off"
    allowed_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "security"
      - match:
          dependency_type: "direct"
          update_type: "security"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    target_branch: "prod"
    allowed_updates:
      - match:
          dependency_type: "development"
          # Supported dependency types:
          # - "development"
          #   Development dependency group (supported by some package managers)
          # - "production"
          #   Production dependency group (supported by some package managers)
          # - "direct"
          #   Direct/top-level dependencies
          # - "indirect"
          #   Indirect/transient/sub-dependencies
          # - "all"
          update_type: "security"
          # Supported update types:
          # - "security"
          # - "all"
      - match:
          dependency_type: "production"
          update_type: "security"
