fragment ParagraphWebform on ParagraphWebform {
  componentId: fieldParagraphId
  title: fieldTitle
  webform: fieldWebform {
    entity {
      ...Webform
    }
  }
}

fragment Webform on Webform {
  id
  title
  description
  status
  path
  form
}
