fragment ParagraphIconHighlight on ParagraphIconHighlight {
  componentId: fieldParagraphId
  title: fieldTitle
  text: fieldText {
    processed
  }
  iconTeasers: fieldContentIcon {
    entity {
      ...ParagraphIconTeaser
    }
  }
  link: fieldPtLink {
    entity {
      ...ParagraphLink
    }
  }
}
