fragment Paragraph on Paragraph {
  type: __typename
  ...ParagraphGallery
  ...ParagraphImage
  ...ParagraphLink
  ...ParagraphMedia
  ...ParagraphMultiColumn
  ...ParagraphSlider
  ...ParagraphText
}
