fragment Paragraph on Paragraph {
  type: __typename
  ...ParagraphGallery
  ...ParagraphHighlight
  ...ParagraphIconHighlight
  ...ParagraphIconTeaser
  ...ParagraphImage
  ...ParagraphLink
  ...ParagraphLinkBgMedia
  ...ParagraphManualTeaser
  ...ParagraphMedia
  ...ParagraphMultiColumn
  ...ParagraphSlider
  ...ParagraphTeaser
  ...ParagraphText
  ...ParagraphTextBgMedia
  ...ParagraphTextWithMedia
}
