fragment Paragraph on Paragraph {
  type: __typename
  ...ParagraphGallery
  ...ParagraphHighlight
  ...ParagraphHighlightSlider
  ...ParagraphIconHighlight
  ...ParagraphIconTeaser
  ...ParagraphImage
  ...ParagraphLink
  ...ParagraphLinkBgMedia
  ...ParagraphManualTeaser
  ...ParagraphMedia
  ...ParagraphSlider
  ...ParagraphTeaser
  ...ParagraphText
  ...ParagraphTextBgMedia
  ...ParagraphTextWithMedia
  ...ParagraphWebform
  ...ParagraphLogoCloud
  ...ParagraphLogo
}
